CREATE TABLE "Classes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Classes" PRIMARY KEY ("Id")
);


CREATE TABLE "Subjects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ClassId" integer NOT NULL,
    CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subjects_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "ClassId" integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes" ("Id")
);


CREATE TABLE "Assignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text,
    "Deadline" timestamp with time zone NOT NULL,
    "MaxMarks" integer NOT NULL,
    "Status" text NOT NULL DEFAULT 'Draft',
    "SubjectId" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "FilePath" text,
    "FileName" text,
    "FileContentType" text,
    "FileSize" bigint,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "PublishedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Assignments_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Assignments_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "TeacherSubjectAssignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeacherId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    CONSTRAINT "PK_TeacherSubjectAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TeacherSubjectAssignments_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TeacherSubjectAssignments_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Submissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AssignmentId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "Content" text,
    "FilePath" text,
    "FileName" text,
    "FileContentType" text,
    "FileSize" bigint,
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "SubmissionStatus" text NOT NULL DEFAULT 'Submitted',
    "GradingStatus" text NOT NULL DEFAULT 'Pending',
    "Marks" integer,
    "Feedback" text,
    "GradedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Submissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Submissions_Assignments_AssignmentId" FOREIGN KEY ("AssignmentId") REFERENCES "Assignments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Submissions_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Assignments_SubjectId" ON "Assignments" ("SubjectId");


CREATE INDEX "IX_Assignments_TeacherId" ON "Assignments" ("TeacherId");


CREATE INDEX "IX_Subjects_ClassId" ON "Subjects" ("ClassId");


CREATE UNIQUE INDEX "IX_Subjects_Name_ClassId" ON "Subjects" ("Name", "ClassId");


CREATE UNIQUE INDEX "IX_Submissions_AssignmentId_StudentId" ON "Submissions" ("AssignmentId", "StudentId");


CREATE INDEX "IX_Submissions_StudentId" ON "Submissions" ("StudentId");


CREATE INDEX "IX_TeacherSubjectAssignments_SubjectId" ON "TeacherSubjectAssignments" ("SubjectId");


CREATE UNIQUE INDEX "IX_TeacherSubjectAssignments_TeacherId_SubjectId" ON "TeacherSubjectAssignments" ("TeacherId", "SubjectId");


CREATE INDEX "IX_Users_ClassId" ON "Users" ("ClassId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


